image: ${CI_REGISTRY}/efabre/b2rust:docker-b2rust

stages:
  - CMake
  - Build
  - Test
  
before_script:
  - apt-get update
  - apt-get install -y libboost-all-dev

cmake-job :
  stage: CMake
  script:
  - echo "CMake Configuration..."
  - cmake -B build -S .  -G "Unix Makefiles"
  - ls build/
  - echo "CMake Configuration successfull"
  tags:
    [docker-linux]
  artifacts:
    paths:
      - build

build-job:
  stage: Build
  script: 
  - echo "Building... "
  - cmake --build build 
  - ls bin/
  - echo "Building successfull !"
  tags:
    [docker-linux]

  artifacts:
    paths:
      - bin

test-job:
  stage: Test
  script:
  - export B2RUST_CONF_HOME=$PWD/files
  - echo "Testing..."
  - ctest --test-dir build 


  tags:
    [docker-linux]

  
